name: 'Hologit Projector'
description: 'Generate and push a holobranch projection'
inputs:
    ref:
      description: 'Name of branch/ref to read source tree from'
      required: false
    holobranch:
      description: 'Name of holobranch to project'
      required: true
    commit-to:
      description: 'Name of branch/ref to optionally commit result to'
      required: false
outputs:
  tree:
    description: 'Tree hash for last projection'
  commit:
    description: 'Commit hash for last projection (if commit-to is configured)'
runs:
  using: 'node12'
  main: 'index.js'
  post: 'post.js'
