name: Public Actions to v1 stream

on:
  push:
    branches: [master]


jobs:
  publish-actions-v1:
    runs-on: ubuntu-latest
    steps:
    - name: 'Update holobranch: actions/projector/v1'
      uses: JarvusInnovations/hologit@actions/projector/v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HAB_LICENSE: accept
      with:
        ref: master
        holobranch: github-action-projector
        commit-to: actions/projector/v1
